language: node_js
node_js:
- node
branches:
  only:
  - master
addons:
  ssh_known_hosts: ssh.stanrogo.com
before_deploy:
- openssl aes-256-cbc -K $encrypted_bf1369b156a9_key -iv $encrypted_bf1369b156a9_iv -in deploy_snake_rsa.enc -out deploy_snake_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_snake_rsa
- ssh-add deploy_snake_rsa
script:
- npm install -g typescript
- tsc
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete -q $TRAVIS_BUILD_DIR/ stanrogo@ssh.stanrogo.com:/home/stanrogo/public_html/snake.stanrogo.com
  on:
    branch: master
